export const metadata = {
  title: "Blog list",
  description: "Generated by Rio",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
